version: "3.9"
services:
  test-db:
    image: postgres:16.2-alpine
    container_name: test-db
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
